### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by reverie** [jaysonsantos/django-bmemcached#5]
This package doesn't support python 3. It would be great if it did! Issue I'm hitting is with the relative vs. absolute import syntax in __init__.py.

**Comment by tomtom5152** [comment]
This appears to have been fixed in 0809679 but is not yet present in the PyPi package (hence pip does not register it). Any chance this could be updated?

**Comment by jaysonsantos** [comment]
Hi @tomtom5152 python-binary-memcached don't support python3 yet, I started this branch https://github.com/jaysonsantos/python-binary-memcached/tree/py34 but couldn't finish yet.

**Comment by tomtom5152** [comment]
Ah great, was just wondering as the commit s where there and I could get it
working at a basic level by cloning the repository. Thanks for the response.

On Wed, 22 Jul 2015 at 09:56 Jayson Reis <notifications@github.com> wrote:

> Hi @tomtom5152 <https://github.com/tomtom5152> python-binary-memcached
> don't support python3 yet, I started this branch
> https://github.com/jaysonsantos/python-binary-memcached/tree/py34 but
> couldn't finish yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaysonsantos/django-bmemcached/issues/5#issuecomment-123626812>
> .
>
-- 

Tom Price

**Comment by mflaxman** [comment]
It would be great if the README noted that python3 isn't supported. I just wasted a bit of time on this :(

**Comment by jaysonsantos** [comment]
@mflaxman It is supposed to support as https://github.com/jaysonsantos/python-binary-memcached/ already support it. But I was careless and didn't add tests, I will check and close this issue.

**Comment by jaysonsantos** [comment]
Actually I changed travis to build python 3 also.
https://travis-ci.org/jaysonsantos/django-bmemcached
